import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';

function runtimeConfigPlugin() {
  return {
    name: 'bazunia-runtime-config',
    configureServer(server) {
      const env = loadEnv(server.config.mode, process.cwd(), '');
      server.middlewares.use('/js/runtime-config.js', (_req, res) => {
        const convexUrl = env.BAZUNIA_CONVEX_URL || env.BAZA_CONVEX_URL || env.CONVEX_URL || '';
        const provider = env.BAZUNIA_PUBLIC_DECK_PROVIDER || env.BAZA_PUBLIC_DECK_PROVIDER || (convexUrl ? 'convex' : 'static');
        res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
        res.end([
          '// runtime-config.js - generated by Vite dev server',
          `window.__BAZUNIA_CONVEX_URL = ${JSON.stringify(convexUrl)};`,
          `window.__BAZUNIA_PUBLIC_DECK_PROVIDER = ${JSON.stringify(provider)};`,
          '',
        ].join('\n'));
      });
    },
  };
}

export default defineConfig({
  plugins: [runtimeConfigPlugin(), react()],
  build: {
    outDir: 'dist',
    emptyOutDir: true,
  },
});
